apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab3-probe-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab3-probe
  template:
    metadata:
      labels:
        app: lab3-probe
    spec:
      containers:
      - name: flask-app
        image: lab3-multi
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
