apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab3-deployment
  labels:
    app: lab3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab3
  template:
    metadata:
      labels:
        app: lab3
    spec:
      containers:
      - name: flask-app
        image: lab3-multi
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
